### ISSUE TITLE
How to access models inside of static methods

### ISSUE THREAD

**Issue by jonjaques** [ConciergeAuctions/sequelize-classes#16]
Hello, I was wondering if there is a way to access the fully built model from inside a static method?

```
class Product extends Model {
  static download(id) {
    return downloadFromSource(id).then(p => Product.build(p))     // build() is not defined
  }
}
```
but this works
```
builder.base.Product.build(...) 
```

Also, the way I have my models defined—I'm importing all of them into where Builder is instantiated, and then exporting that. So I can't import that instance into my models or I would have a circular dep.

Is there a way to circumvent this? I noticed there is a `Model.exportModel()` but I'm unsure of how to wire that up.

Thank you! Great module btw.

**Comment by jonjaques** [comment]
Also, before finding this module - I had my own crappy es6 model implementation, the way I did it was to add a reference to the `builder` when I'm registering models.

So that way inside my static methods I could do this:
```
static download() {
  const {Product, Variant} = Product.db.models
  // ...
}

I took a brief tour through the code trying to pinpoint if this is already available, but no luck. I'd be happy to send a PR if you could point me to the right place in the code to do that.

**Comment by brad-decker** [comment]
hi @jonjaques 

The static function isn't actually going to be called directly against the model created within your Product file, but instead will be called against the built model added to the builder base. So basically you would just do 

``` 
class Product extends Model {
  static download(id) {
    return downloadFromSource(id).then(p => this.build(p))
  }
}
```

**Comment by jonjaques** [comment]
Thanks a bunch! It's all clicking now :smile:
